
id: am-net
version: 0.7.0
type: library
dependencies:
  - id: am-lang-core
    realm: github
    type: git-repo
    tag: latest
    branch: master
    url: https://github.com/anderskjeldsen/am-lang-core.git
platforms:
  - id: libc
    abstract: true
  - id: amigaos
    extends: libc
    gccCommand: m68k-amigaos-gcc -O3
    asmCommand: vasmm68k_mot
    additionalHeaders:
    additionalAsmSources:
    additionalCSources: 
    additionalIncludePaths:
    gccAdditionalOptions:
      - -noixemul     
    gccAdditionalLibraries:
      - socket
  - id: morphos-ppc
    extends: libc
    gccCommand: ppc-morphos-gcc -O3
    additionalHeaders:
    additionalAsmSources:
    additionalCSources: 
    additionalIncludePaths:
    gccAdditionalOptions:
      - -noixemul     
    gccAdditionalLibraries:
  - id: macos
    extends: libc
    gccCommand: gcc -O3
    additionalHeaders:
    additionalAsmSources:
    additionalCSources: 
    additionalIncludePaths:
    gccAdditionalOptions:
    gccAdditionalLibraries:
  - id: macos-arm
    extends: libc
    gccCommand: gcc -O3
    additionalHeaders:
    additionalAsmSources:
    additionalCSources: 
    additionalIncludePaths:
    gccAdditionalOptions:
    gccAdditionalLibraries:
  - id: linux-x64
    extends: libc
    gccCommand: gcc -O3
    additionalHeaders:
    additionalAsmSources:
    additionalCSources: 
    additionalIncludePaths:
    gccAdditionalOptions:
    gccAdditionalLibraries:

buildTargets:
  - id: amigaos_docker
    platform: amigaos
    dockerBuild:
      image: amiga-gcc
      buildPath: /host
  - id: morphos-ppc_docker
    platform: morphos-ppc
    dockerBuild:
      image: amigadev/crosstools:ppc-morphos
      buildPath: /work
  - id: macos
    platform: macos
  - id: macos-arm
    platform: macos-arm
  - id: linux-x64
    platform: linux-x64
