#pragma once
#include <libc/core.h>
#include <Am/Net/Socket.h>
#include <Am/Lang/ClassRef.h>
#include <Am/Lang/Object.h>
#include <Am/Net/AddressFamily.h>
#include <Am/Net/SocketType.h>
#include <Am/Net/ProtocolFamily.h>
#include <Am/Lang/String.h>
#include <Am/Lang/Int.h>
#include <Am/Lang/UInt.h>
#include <Am/Lang/UByte.h>
#include <Am/Lang/Array.h>
